version: "2"

networks:
  cc-mensalist-net:
    external: true

services:
  intermediate-container:
    image: node:carbon
    ports:
      - 1180:80
    command: bash -c 'npm install'
    volumes:
      - ./:/rest-server
    env_file:
      - .env
    environment:
      - DOCKER=1
      - CHANNEL=mainchannel
      - CCNAME=cc-mensalist
    working_dir: /rest-server
    container_name: intermediate-container
    networks:
      - cc-mensalist-net
      