name: Tests

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  build:
    defaults:
      run:
        shell: bash
        working-directory: chaincode
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16      

    - name: Build
      run: go build -v github.com/goledgerdev/cc-mensalist/chaincode

    - name: Test
      run: go test github.com/goledgerdev/cc-mensalist/chaincode -coverpkg=./... -v